# -*- coding: utf-8 -*-
"""Assignment 1 : Day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rMQhG1xCKEgnGfH5xxbX20nFcaXlnUp-
"""

#Assignment 1 : Day 3

plane=1000
if plane < 1000 :
  print("land the plane")
elif plane > 1000 and plane < 5000 :
  print("come down to 1000")
elif plane < 5000 :
  print("go around and try later")